services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
  snack-shop-be:
    build: .
    restart: always
    ports: 
      - '8080:8080'
    depends_on:
      - mongodb